mode: predict
debug: False
load_ckpt: experiments/vm/checkpoint_99.pkl

components:
  data: predict_noisy_test
  transform: predict_npy
  system: vm
  model: vm

writer:
  __target__: vm
  save_dir: denoisy_test_raw
  save_name: denoised
