mode: predict
debug: False
load_ckpt: /root/autodl-tmp/experiments/paired_straight_vm_from_b2ft10_nf3000_b2_lr5e5_10ep/checkpoint_9.pkl

components:
  data: predict_noisy_test_autodl_tmp
  transform: predict_npy
  system: vm
  model: dcvm

writer:
  __target__: vm
  save_dir: /root/autodl-tmp/paired_straight_vm_denoisy_test_raw
  save_name: denoised
