mode: predict
debug: False
load_ckpt: /root/autodl-tmp/experiments/v1.4d_cdrefine_attn_cdset/checkpoint_5.pkl

components:
  data: predict_noisy_test_autodl_tmp
  transform: predict_npy
  system: vm
  model: v1_4d_cdrefine_attn_cdset_predict_tmp

writer:
  __target__: vm
  save_dir: /root/autodl-tmp/v1.4d_cdrefine_attn_cdset_noisy_test_raw
  save_name: denoised
