mode: predict
debug: False
load_ckpt: experiments/surface_straight_vm/checkpoint_19.pkl

components:
  data: predict
  transform: predict_npy
  system: vm
  model: dcvm

writer:
  __target__: vm
  save_dir: tmp_predict_surface_straight_vm
  save_name: denoised
