mode: predict
debug: False
load_ckpt: /root/autodl-tmp/jittor_pcd/experiments/dcvm_v2/checkpoint_99.pkl

components:
  data: predict
  transform: predict_npy
  system: vm
  model: dcvm_v2

writer:
  __target__: vm
  save_dir: /root/autodl-tmp/jittor_pcd/dcvm_v2_submit_result_raw
  save_name: denoised
