mode: predict
debug: False
load_ckpt: /root/autodl-tmp/experiments/v1.4b_cdrefine_attn_p2s/checkpoint_3.pkl

components:
  data: predict_submit_autodl_tmp
  transform: predict_npy
  system: vm
  model: v1_4b_cdrefine_attn_p2s_predict_tmp

writer:
  __target__: vm
  save_dir: /root/autodl-tmp/v1.4b_official_submit_raw
  save_name: denoised
