mode: train
debug: False

components:
  data: train_surface_straight_autodl_tmp
  transform: surface_straight
  system: dcvm_autodl_tmp
  model: dcvm

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.0001

trainer:
  epochs: 20
