mode: train
debug: False
load_ckpt: /root/autodl-tmp/experiments/surface_straight_vm_from32_nf3000_b2_lr5e5_40ep/checkpoint_9.pkl

components:
  data: train_paired_straight_autodl_tmp
  transform: paired_straight
  system: paired_straight_vm_from_b2ft10_autodl_tmp
  model: dcvm

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.00005

trainer:
  epochs: 10
