mode: train
debug: False

components:
  data: train_refine_v1_3b_tmp
  transform: cache_passthrough_tmp
  system: v1_4a_cdrefine_attn_tmp
  model: v1_4a_cdrefine_attn_tmp

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.00005

trainer:
  epochs: 4
